package com.EnergyProject.dao;


import com.EnergyProject.pojo.Shiro_username;
import com.EnergyProject.pojo.Shiro_usernameExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface Shiro_usernameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_username
     *
     * @mbggenerated Tue Apr 27 10:06:13 CST 2021
     */
    int countByExample(Shiro_usernameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_username
     *
     * @mbggenerated Tue Apr 27 10:06:13 CST 2021
     */
    int deleteByExample(Shiro_usernameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_username
     *
     * @mbggenerated Tue Apr 27 10:06:13 CST 2021
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_username
     *
     * @mbggenerated Tue Apr 27 10:06:13 CST 2021
     */
    int insert(Shiro_username record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_username
     *
     * @mbggenerated Tue Apr 27 10:06:13 CST 2021
     */
    int insertSelective(Shiro_username record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_username
     *
     * @mbggenerated Tue Apr 27 10:06:13 CST 2021
     */
    List<Shiro_username> selectByExampleWithBLOBs(Shiro_usernameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_username
     *
     * @mbggenerated Tue Apr 27 10:06:13 CST 2021
     */
    List<Shiro_username> selectByExample(Shiro_usernameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_username
     *
     * @mbggenerated Tue Apr 27 10:06:13 CST 2021
     */
    Shiro_username selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_username
     *
     * @mbggenerated Tue Apr 27 10:06:13 CST 2021
     */
    int updateByExampleSelective(@Param("record") Shiro_username record, @Param("example") Shiro_usernameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_username
     *
     * @mbggenerated Tue Apr 27 10:06:13 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") Shiro_username record, @Param("example") Shiro_usernameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_username
     *
     * @mbggenerated Tue Apr 27 10:06:13 CST 2021
     */
    int updateByExample(@Param("record") Shiro_username record, @Param("example") Shiro_usernameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_username
     *
     * @mbggenerated Tue Apr 27 10:06:13 CST 2021
     */
    int updateByPrimaryKeySelective(Shiro_username record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_username
     *
     * @mbggenerated Tue Apr 27 10:06:13 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(Shiro_username record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_username
     *
     * @mbggenerated Tue Apr 27 10:06:13 CST 2021
     */
    int updateByPrimaryKey(Shiro_username record);
    String getsalt(String username);
}