package com.pojo;

public class DefectrecordWithBLOBs extends Defectrecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectrecord.defect_photo
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    private byte[] defectPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectrecord.defect_photo2
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    private byte[] defectPhoto2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectrecord.defect_photo3
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    private byte[] defectPhoto3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectrecord.defect_photo4
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    private byte[] defectPhoto4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defectrecord.defect_photo
     *
     * @return the value of defectrecord.defect_photo
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    public byte[] getDefectPhoto() {
        return defectPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defectrecord.defect_photo
     *
     * @param defectPhoto the value for defectrecord.defect_photo
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    public void setDefectPhoto(byte[] defectPhoto) {
        this.defectPhoto = defectPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defectrecord.defect_photo2
     *
     * @return the value of defectrecord.defect_photo2
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    public byte[] getDefectPhoto2() {
        return defectPhoto2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defectrecord.defect_photo2
     *
     * @param defectPhoto2 the value for defectrecord.defect_photo2
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    public void setDefectPhoto2(byte[] defectPhoto2) {
        this.defectPhoto2 = defectPhoto2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defectrecord.defect_photo3
     *
     * @return the value of defectrecord.defect_photo3
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    public byte[] getDefectPhoto3() {
        return defectPhoto3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defectrecord.defect_photo3
     *
     * @param defectPhoto3 the value for defectrecord.defect_photo3
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    public void setDefectPhoto3(byte[] defectPhoto3) {
        this.defectPhoto3 = defectPhoto3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defectrecord.defect_photo4
     *
     * @return the value of defectrecord.defect_photo4
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    public byte[] getDefectPhoto4() {
        return defectPhoto4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defectrecord.defect_photo4
     *
     * @param defectPhoto4 the value for defectrecord.defect_photo4
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    public void setDefectPhoto4(byte[] defectPhoto4) {
        this.defectPhoto4 = defectPhoto4;
    }
}