package com.pojo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DefectrecordExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    public DefectrecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVinIsNull() {
            addCriterion("VIN is null");
            return (Criteria) this;
        }

        public Criteria andVinIsNotNull() {
            addCriterion("VIN is not null");
            return (Criteria) this;
        }

        public Criteria andVinEqualTo(String value) {
            addCriterion("VIN =", value, "vin");
            return (Criteria) this;
        }

        public Criteria andVinNotEqualTo(String value) {
            addCriterion("VIN <>", value, "vin");
            return (Criteria) this;
        }

        public Criteria andVinGreaterThan(String value) {
            addCriterion("VIN >", value, "vin");
            return (Criteria) this;
        }

        public Criteria andVinGreaterThanOrEqualTo(String value) {
            addCriterion("VIN >=", value, "vin");
            return (Criteria) this;
        }

        public Criteria andVinLessThan(String value) {
            addCriterion("VIN <", value, "vin");
            return (Criteria) this;
        }

        public Criteria andVinLessThanOrEqualTo(String value) {
            addCriterion("VIN <=", value, "vin");
            return (Criteria) this;
        }

        public Criteria andVinLike(String value) {
            addCriterion("VIN like", value, "vin");
            return (Criteria) this;
        }

        public Criteria andVinNotLike(String value) {
            addCriterion("VIN not like", value, "vin");
            return (Criteria) this;
        }

        public Criteria andVinIn(List<String> values) {
            addCriterion("VIN in", values, "vin");
            return (Criteria) this;
        }

        public Criteria andVinNotIn(List<String> values) {
            addCriterion("VIN not in", values, "vin");
            return (Criteria) this;
        }

        public Criteria andVinBetween(String value1, String value2) {
            addCriterion("VIN between", value1, value2, "vin");
            return (Criteria) this;
        }

        public Criteria andVinNotBetween(String value1, String value2) {
            addCriterion("VIN not between", value1, value2, "vin");
            return (Criteria) this;
        }

        public Criteria andCarTypeIsNull() {
            addCriterion("car_type is null");
            return (Criteria) this;
        }

        public Criteria andCarTypeIsNotNull() {
            addCriterion("car_type is not null");
            return (Criteria) this;
        }

        public Criteria andCarTypeEqualTo(String value) {
            addCriterion("car_type =", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeNotEqualTo(String value) {
            addCriterion("car_type <>", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeGreaterThan(String value) {
            addCriterion("car_type >", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeGreaterThanOrEqualTo(String value) {
            addCriterion("car_type >=", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeLessThan(String value) {
            addCriterion("car_type <", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeLessThanOrEqualTo(String value) {
            addCriterion("car_type <=", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeLike(String value) {
            addCriterion("car_type like", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeNotLike(String value) {
            addCriterion("car_type not like", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeIn(List<String> values) {
            addCriterion("car_type in", values, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeNotIn(List<String> values) {
            addCriterion("car_type not in", values, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeBetween(String value1, String value2) {
            addCriterion("car_type between", value1, value2, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeNotBetween(String value1, String value2) {
            addCriterion("car_type not between", value1, value2, "carType");
            return (Criteria) this;
        }

        public Criteria andDefectStatusIsNull() {
            addCriterion("defect_status is null");
            return (Criteria) this;
        }

        public Criteria andDefectStatusIsNotNull() {
            addCriterion("defect_status is not null");
            return (Criteria) this;
        }

        public Criteria andDefectStatusEqualTo(String value) {
            addCriterion("defect_status =", value, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusNotEqualTo(String value) {
            addCriterion("defect_status <>", value, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusGreaterThan(String value) {
            addCriterion("defect_status >", value, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusGreaterThanOrEqualTo(String value) {
            addCriterion("defect_status >=", value, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusLessThan(String value) {
            addCriterion("defect_status <", value, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusLessThanOrEqualTo(String value) {
            addCriterion("defect_status <=", value, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusLike(String value) {
            addCriterion("defect_status like", value, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusNotLike(String value) {
            addCriterion("defect_status not like", value, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusIn(List<String> values) {
            addCriterion("defect_status in", values, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusNotIn(List<String> values) {
            addCriterion("defect_status not in", values, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusBetween(String value1, String value2) {
            addCriterion("defect_status between", value1, value2, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusNotBetween(String value1, String value2) {
            addCriterion("defect_status not between", value1, value2, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andStationIsNull() {
            addCriterion("station is null");
            return (Criteria) this;
        }

        public Criteria andStationIsNotNull() {
            addCriterion("station is not null");
            return (Criteria) this;
        }

        public Criteria andStationEqualTo(String value) {
            addCriterion("station =", value, "station");
            return (Criteria) this;
        }

        public Criteria andStationNotEqualTo(String value) {
            addCriterion("station <>", value, "station");
            return (Criteria) this;
        }

        public Criteria andStationGreaterThan(String value) {
            addCriterion("station >", value, "station");
            return (Criteria) this;
        }

        public Criteria andStationGreaterThanOrEqualTo(String value) {
            addCriterion("station >=", value, "station");
            return (Criteria) this;
        }

        public Criteria andStationLessThan(String value) {
            addCriterion("station <", value, "station");
            return (Criteria) this;
        }

        public Criteria andStationLessThanOrEqualTo(String value) {
            addCriterion("station <=", value, "station");
            return (Criteria) this;
        }

        public Criteria andStationLike(String value) {
            addCriterion("station like", value, "station");
            return (Criteria) this;
        }

        public Criteria andStationNotLike(String value) {
            addCriterion("station not like", value, "station");
            return (Criteria) this;
        }

        public Criteria andStationIn(List<String> values) {
            addCriterion("station in", values, "station");
            return (Criteria) this;
        }

        public Criteria andStationNotIn(List<String> values) {
            addCriterion("station not in", values, "station");
            return (Criteria) this;
        }

        public Criteria andStationBetween(String value1, String value2) {
            addCriterion("station between", value1, value2, "station");
            return (Criteria) this;
        }

        public Criteria andStationNotBetween(String value1, String value2) {
            addCriterion("station not between", value1, value2, "station");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNull() {
            addCriterion("timestamp is null");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNotNull() {
            addCriterion("timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampEqualTo(Date value) {
            addCriterion("timestamp =", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotEqualTo(Date value) {
            addCriterion("timestamp <>", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThan(Date value) {
            addCriterion("timestamp >", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("timestamp >=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThan(Date value) {
            addCriterion("timestamp <", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThanOrEqualTo(Date value) {
            addCriterion("timestamp <=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampIn(List<Date> values) {
            addCriterion("timestamp in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotIn(List<Date> values) {
            addCriterion("timestamp not in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampBetween(Date value1, Date value2) {
            addCriterion("timestamp between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotBetween(Date value1, Date value2) {
            addCriterion("timestamp not between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andDefectPartIsNull() {
            addCriterion("defect_part is null");
            return (Criteria) this;
        }

        public Criteria andDefectPartIsNotNull() {
            addCriterion("defect_part is not null");
            return (Criteria) this;
        }

        public Criteria andDefectPartEqualTo(String value) {
            addCriterion("defect_part =", value, "defectPart");
            return (Criteria) this;
        }

        public Criteria andDefectPartNotEqualTo(String value) {
            addCriterion("defect_part <>", value, "defectPart");
            return (Criteria) this;
        }

        public Criteria andDefectPartGreaterThan(String value) {
            addCriterion("defect_part >", value, "defectPart");
            return (Criteria) this;
        }

        public Criteria andDefectPartGreaterThanOrEqualTo(String value) {
            addCriterion("defect_part >=", value, "defectPart");
            return (Criteria) this;
        }

        public Criteria andDefectPartLessThan(String value) {
            addCriterion("defect_part <", value, "defectPart");
            return (Criteria) this;
        }

        public Criteria andDefectPartLessThanOrEqualTo(String value) {
            addCriterion("defect_part <=", value, "defectPart");
            return (Criteria) this;
        }

        public Criteria andDefectPartLike(String value) {
            addCriterion("defect_part like", value, "defectPart");
            return (Criteria) this;
        }

        public Criteria andDefectPartNotLike(String value) {
            addCriterion("defect_part not like", value, "defectPart");
            return (Criteria) this;
        }

        public Criteria andDefectPartIn(List<String> values) {
            addCriterion("defect_part in", values, "defectPart");
            return (Criteria) this;
        }

        public Criteria andDefectPartNotIn(List<String> values) {
            addCriterion("defect_part not in", values, "defectPart");
            return (Criteria) this;
        }

        public Criteria andDefectPartBetween(String value1, String value2) {
            addCriterion("defect_part between", value1, value2, "defectPart");
            return (Criteria) this;
        }

        public Criteria andDefectPartNotBetween(String value1, String value2) {
            addCriterion("defect_part not between", value1, value2, "defectPart");
            return (Criteria) this;
        }

        public Criteria andSpecificPartIsNull() {
            addCriterion("specific_part is null");
            return (Criteria) this;
        }

        public Criteria andSpecificPartIsNotNull() {
            addCriterion("specific_part is not null");
            return (Criteria) this;
        }

        public Criteria andSpecificPartEqualTo(String value) {
            addCriterion("specific_part =", value, "specificPart");
            return (Criteria) this;
        }

        public Criteria andSpecificPartNotEqualTo(String value) {
            addCriterion("specific_part <>", value, "specificPart");
            return (Criteria) this;
        }

        public Criteria andSpecificPartGreaterThan(String value) {
            addCriterion("specific_part >", value, "specificPart");
            return (Criteria) this;
        }

        public Criteria andSpecificPartGreaterThanOrEqualTo(String value) {
            addCriterion("specific_part >=", value, "specificPart");
            return (Criteria) this;
        }

        public Criteria andSpecificPartLessThan(String value) {
            addCriterion("specific_part <", value, "specificPart");
            return (Criteria) this;
        }

        public Criteria andSpecificPartLessThanOrEqualTo(String value) {
            addCriterion("specific_part <=", value, "specificPart");
            return (Criteria) this;
        }

        public Criteria andSpecificPartLike(String value) {
            addCriterion("specific_part like", value, "specificPart");
            return (Criteria) this;
        }

        public Criteria andSpecificPartNotLike(String value) {
            addCriterion("specific_part not like", value, "specificPart");
            return (Criteria) this;
        }

        public Criteria andSpecificPartIn(List<String> values) {
            addCriterion("specific_part in", values, "specificPart");
            return (Criteria) this;
        }

        public Criteria andSpecificPartNotIn(List<String> values) {
            addCriterion("specific_part not in", values, "specificPart");
            return (Criteria) this;
        }

        public Criteria andSpecificPartBetween(String value1, String value2) {
            addCriterion("specific_part between", value1, value2, "specificPart");
            return (Criteria) this;
        }

        public Criteria andSpecificPartNotBetween(String value1, String value2) {
            addCriterion("specific_part not between", value1, value2, "specificPart");
            return (Criteria) this;
        }

        public Criteria andDefectModeIsNull() {
            addCriterion("defect_mode is null");
            return (Criteria) this;
        }

        public Criteria andDefectModeIsNotNull() {
            addCriterion("defect_mode is not null");
            return (Criteria) this;
        }

        public Criteria andDefectModeEqualTo(String value) {
            addCriterion("defect_mode =", value, "defectMode");
            return (Criteria) this;
        }

        public Criteria andDefectModeNotEqualTo(String value) {
            addCriterion("defect_mode <>", value, "defectMode");
            return (Criteria) this;
        }

        public Criteria andDefectModeGreaterThan(String value) {
            addCriterion("defect_mode >", value, "defectMode");
            return (Criteria) this;
        }

        public Criteria andDefectModeGreaterThanOrEqualTo(String value) {
            addCriterion("defect_mode >=", value, "defectMode");
            return (Criteria) this;
        }

        public Criteria andDefectModeLessThan(String value) {
            addCriterion("defect_mode <", value, "defectMode");
            return (Criteria) this;
        }

        public Criteria andDefectModeLessThanOrEqualTo(String value) {
            addCriterion("defect_mode <=", value, "defectMode");
            return (Criteria) this;
        }

        public Criteria andDefectModeLike(String value) {
            addCriterion("defect_mode like", value, "defectMode");
            return (Criteria) this;
        }

        public Criteria andDefectModeNotLike(String value) {
            addCriterion("defect_mode not like", value, "defectMode");
            return (Criteria) this;
        }

        public Criteria andDefectModeIn(List<String> values) {
            addCriterion("defect_mode in", values, "defectMode");
            return (Criteria) this;
        }

        public Criteria andDefectModeNotIn(List<String> values) {
            addCriterion("defect_mode not in", values, "defectMode");
            return (Criteria) this;
        }

        public Criteria andDefectModeBetween(String value1, String value2) {
            addCriterion("defect_mode between", value1, value2, "defectMode");
            return (Criteria) this;
        }

        public Criteria andDefectModeNotBetween(String value1, String value2) {
            addCriterion("defect_mode not between", value1, value2, "defectMode");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andDefectNameIsNull() {
            addCriterion("defect_name is null");
            return (Criteria) this;
        }

        public Criteria andDefectNameIsNotNull() {
            addCriterion("defect_name is not null");
            return (Criteria) this;
        }

        public Criteria andDefectNameEqualTo(String value) {
            addCriterion("defect_name =", value, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameNotEqualTo(String value) {
            addCriterion("defect_name <>", value, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameGreaterThan(String value) {
            addCriterion("defect_name >", value, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameGreaterThanOrEqualTo(String value) {
            addCriterion("defect_name >=", value, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameLessThan(String value) {
            addCriterion("defect_name <", value, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameLessThanOrEqualTo(String value) {
            addCriterion("defect_name <=", value, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameLike(String value) {
            addCriterion("defect_name like", value, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameNotLike(String value) {
            addCriterion("defect_name not like", value, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameIn(List<String> values) {
            addCriterion("defect_name in", values, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameNotIn(List<String> values) {
            addCriterion("defect_name not in", values, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameBetween(String value1, String value2) {
            addCriterion("defect_name between", value1, value2, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameNotBetween(String value1, String value2) {
            addCriterion("defect_name not between", value1, value2, "defectName");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNull() {
            addCriterion("comments is null");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNotNull() {
            addCriterion("comments is not null");
            return (Criteria) this;
        }

        public Criteria andCommentsEqualTo(String value) {
            addCriterion("comments =", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotEqualTo(String value) {
            addCriterion("comments <>", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThan(String value) {
            addCriterion("comments >", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("comments >=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThan(String value) {
            addCriterion("comments <", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThanOrEqualTo(String value) {
            addCriterion("comments <=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLike(String value) {
            addCriterion("comments like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotLike(String value) {
            addCriterion("comments not like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsIn(List<String> values) {
            addCriterion("comments in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotIn(List<String> values) {
            addCriterion("comments not in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsBetween(String value1, String value2) {
            addCriterion("comments between", value1, value2, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotBetween(String value1, String value2) {
            addCriterion("comments not between", value1, value2, "comments");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table defectrecord
     *
     * @mbggenerated do_not_delete_during_merge Fri May 07 14:32:04 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}