package com.pojo;

import java.io.Serializable;

public class Defectlist implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectlist.id
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectlist.type
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectlist.defect_part
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    private String defectPart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectlist.specific_part
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    private String specificPart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectlist.defect_mode
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    private String defectMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectlist.remark
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defectlist.id
     *
     * @return the value of defectlist.id
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defectlist.id
     *
     * @param id the value for defectlist.id
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defectlist.type
     *
     * @return the value of defectlist.type
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defectlist.type
     *
     * @param type the value for defectlist.type
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defectlist.defect_part
     *
     * @return the value of defectlist.defect_part
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    public String getDefectPart() {
        return defectPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defectlist.defect_part
     *
     * @param defectPart the value for defectlist.defect_part
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    public void setDefectPart(String defectPart) {
        this.defectPart = defectPart == null ? null : defectPart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defectlist.specific_part
     *
     * @return the value of defectlist.specific_part
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    public String getSpecificPart() {
        return specificPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defectlist.specific_part
     *
     * @param specificPart the value for defectlist.specific_part
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    public void setSpecificPart(String specificPart) {
        this.specificPart = specificPart == null ? null : specificPart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defectlist.defect_mode
     *
     * @return the value of defectlist.defect_mode
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    public String getDefectMode() {
        return defectMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defectlist.defect_mode
     *
     * @param defectMode the value for defectlist.defect_mode
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    public void setDefectMode(String defectMode) {
        this.defectMode = defectMode == null ? null : defectMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defectlist.remark
     *
     * @return the value of defectlist.remark
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defectlist.remark
     *
     * @param remark the value for defectlist.remark
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    @Override
    public String toString() {
        return "Defectlist{" +
                "id=" + id +
                ", type='" + type + '\'' +
                ", defectPart='" + defectPart + '\'' +
                ", specificPart='" + specificPart + '\'' +
                ", defectMode='" + defectMode + '\'' +
                ", remark='" + remark + '\'' +
                '}';
    }
}