package com.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.validation.constraints.NotBlank;
import java.io.Serializable;
import java.util.Date;

public class DefectrecordBase64 implements Serializable {

    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectrecord.VIN
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    private String vin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectrecord.station
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    private String station;

    private String carType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectrecord.defect_status
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */

    private String defectStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectrecord.timestamp
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GTM+8")
    private Date timestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectrecord.type
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectrecord.defect_part
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    private String defectPart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectrecord.specific_part
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    private String specificPart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectrecord.defect_mode
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    private String defectMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectrecord.remark
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectrecord.defect_name
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    private String defectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectrecord.status
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectrecord.username
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectrecord.comments
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defectrecord.defect_photo
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    private String defectPhoto;
    private String defectPhoto2;
    private String defectPhoto3;
    private String defectPhoto4;
    private String photourl;
    private String photourl2;
    private String photourl3;
    private String photourl4;

    public DefectrecordBase64() {
    }

    public DefectrecordBase64(Integer id, String vin, String station, Date timestamp, String type, String defectPart, String specificPart, String defectMode, String remark, String defectName, String status, String username, String comments, String defectPhoto, String photourl) {
        this.id = id;
        this.vin = vin;
        this.station = station;
        this.timestamp = timestamp;
        this.type = type;
        this.defectPart = defectPart;
        this.specificPart = specificPart;
        this.defectMode = defectMode;
        this.remark = remark;
        this.defectName = defectName;
        this.status = status;
        this.username = username;
        this.comments = comments;
        this.defectPhoto = defectPhoto;
        this.photourl = photourl;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getVin() {
        return vin;
    }

    public void setVin(String vin) {
        this.vin = vin;
    }

    public String getStation() {
        return station;
    }

    public void setStation(String station) {
        this.station = station;
    }

    public Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getDefectPart() {
        return defectPart;
    }

    public void setDefectPart(String defectPart) {
        this.defectPart = defectPart;
    }

    public String getSpecificPart() {
        return specificPart;
    }

    public void setSpecificPart(String specificPart) {
        this.specificPart = specificPart;
    }

    public String getDefectMode() {
        return defectMode;
    }

    public void setDefectMode(String defectMode) {
        this.defectMode = defectMode;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getDefectName() {
        return defectName;
    }

    public void setDefectName(String defectName) {
        this.defectName = defectName;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getDefectPhoto() {
        return defectPhoto;
    }

    public void setDefectPhoto(String defectPhoto) {
        this.defectPhoto = defectPhoto;
    }

    public String getPhotourl() {
        return photourl;
    }

    public void setPhotourl(String photourl) {
        this.photourl = photourl;
    }

    public String getDefectPhoto2() {
        return defectPhoto2;
    }

    public void setDefectPhoto2(String defectPhoto2) {
        this.defectPhoto2 = defectPhoto2;
    }

    public String getDefectPhoto3() {
        return defectPhoto3;
    }

    public void setDefectPhoto3(String defectPhoto3) {
        this.defectPhoto3 = defectPhoto3;
    }

    public String getDefectPhoto4() {
        return defectPhoto4;
    }

    public void setDefectPhoto4(String defectPhoto4) {
        this.defectPhoto4 = defectPhoto4;
    }

    public String getPhotourl2() {
        return photourl2;
    }

    public void setPhotourl2(String photourl2) {
        this.photourl2 = photourl2;
    }

    public String getPhotourl3() {
        return photourl3;
    }

    public void setPhotourl3(String photourl3) {
        this.photourl3 = photourl3;
    }

    public String getPhotourl4() {
        return photourl4;
    }

    public void setPhotourl4(String photourl4) {
        this.photourl4 = photourl4;
    }

    public String getCarType() {
        return carType;
    }

    public void setCarType(String carType) {
        this.carType = carType;
    }

    public String getDefectStatus() {
        return defectStatus;
    }

    public void setDefectStatus(String defectStatus) {
        this.defectStatus = defectStatus;
    }

    @Override
    public String toString() {
        return "DefectrecordBase64{" +
                "id=" + id +
                ", vin='" + vin + '\'' +
                ", station='" + station + '\'' +
                ", carType='" + carType + '\'' +
                ", defectStatus='" + defectStatus + '\'' +
                ", timestamp=" + timestamp +
                ", type='" + type + '\'' +
                ", defectPart='" + defectPart + '\'' +
                ", specificPart='" + specificPart + '\'' +
                ", defectMode='" + defectMode + '\'' +
                ", remark='" + remark + '\'' +
                ", defectName='" + defectName + '\'' +
                ", status='" + status + '\'' +
                ", username='" + username + '\'' +
                ", comments='" + comments + '\'' +
                ", defectPhoto='" + defectPhoto + '\'' +
                ", defectPhoto2='" + defectPhoto2 + '\'' +
                ", defectPhoto3='" + defectPhoto3 + '\'' +
                ", defectPhoto4='" + defectPhoto4 + '\'' +
                ", photourl='" + photourl + '\'' +
                ", photourl2='" + photourl2 + '\'' +
                ", photourl3='" + photourl3 + '\'' +
                ", photourl4='" + photourl4 + '\'' +
                '}';
    }
}


