package com.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class Shiro_usernameBase64 implements Serializable {

    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_username.username
     *
     * @mbggenerated Fri Apr 23 14:12:56 CST 2021
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_username.password
     *
     * @mbggenerated Fri Apr 23 14:12:56 CST 2021
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_username.salt
     *
     * @mbggenerated Fri Apr 23 14:12:56 CST 2021
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_username.email
     *
     * @mbggenerated Fri Apr 23 14:12:56 CST 2021
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_username.mobile
     *
     * @mbggenerated Fri Apr 23 14:12:56 CST 2021
     */
    private Long mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_username.status
     *
     * @mbggenerated Fri Apr 23 14:12:56 CST 2021
     */
    private String status;


    private String station;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_username.createTime
     *
     * @mbggenerated Fri Apr 23 14:12:56 CST 2021
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GTM+8")
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_username.updateTime
     *
     * @mbggenerated Fri Apr 23 14:12:56 CST 2021
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GTM+8")
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_username.user_photo
     *
     * @mbggenerated Fri Apr 23 14:12:56 CST 2021
     */
    private String userPhoto;

    public Shiro_usernameBase64() {
    }

    public Shiro_usernameBase64(Integer userid, String username, String password, String salt, String email, Long mobile, String status, Date createtime, Date updatetime, String userPhoto) {
        this.userid = userid;
        this.username = username;
        this.password = password;
        this.salt = salt;
        this.email = email;
        this.mobile = mobile;
        this.status = status;
        this.createtime = createtime;
        this.updatetime = updatetime;
        this.userPhoto = userPhoto;
    }

    public Integer getUserid() {
        return userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getSalt() {
        return salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Long getMobile() {
        return mobile;
    }

    public void setMobile(Long mobile) {
        this.mobile = mobile;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public Date getUpdatetime() {
        return updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    public String getUserPhoto() {
        return userPhoto;
    }

    public void setUserPhoto(String userPhoto) {
        this.userPhoto = userPhoto;
    }

    public String getStation() {
        return station;
    }

    public void setStation(String station) {
        this.station = station;
    }

    @Override
    public String toString() {
        return "Shiro_usernameBase64{" +
                "userid=" + userid +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", salt='" + salt + '\'' +
                ", email='" + email + '\'' +
                ", mobile=" + mobile +
                ", status='" + status + '\'' +
                ", station='" + station + '\'' +
                ", createtime=" + createtime +
                ", updatetime=" + updatetime +
                ", userPhoto='" + userPhoto + '\'' +
                '}';
    }
}
