package com.dao;

import com.pojo.Defectlist;
import com.pojo.DefectlistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefectlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectlist
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    int countByExample(DefectlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectlist
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    int deleteByExample(DefectlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectlist
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectlist
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    int insert(Defectlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectlist
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    int insertSelective(Defectlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectlist
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    List<Defectlist> selectByExample(DefectlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectlist
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    Defectlist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectlist
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    int updateByExampleSelective(@Param("record") Defectlist record, @Param("example") DefectlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectlist
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    int updateByExample(@Param("record") Defectlist record, @Param("example") DefectlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectlist
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    int updateByPrimaryKeySelective(Defectlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectlist
     *
     * @mbggenerated Thu Apr 22 09:46:46 CST 2021
     */
    int updateByPrimaryKey(Defectlist record);
}