package com.dao;

import com.pojo.Defectrecord;
import com.pojo.DefectrecordExample;
import com.pojo.DefectrecordWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DefectrecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    int countByExample(DefectrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    int deleteByExample(DefectrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    int insert(DefectrecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    int insertSelective(DefectrecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    List<DefectrecordWithBLOBs> selectByExampleWithBLOBs(DefectrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    List<Defectrecord> selectByExample(DefectrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    DefectrecordWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    int updateByExampleSelective(@Param("record") DefectrecordWithBLOBs record, @Param("example") DefectrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") DefectrecordWithBLOBs record, @Param("example") DefectrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    int updateByExample(@Param("record") Defectrecord record, @Param("example") DefectrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    int updateByPrimaryKeySelective(DefectrecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(DefectrecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defectrecord
     *
     * @mbggenerated Fri May 07 14:32:04 CST 2021
     */
    int updateByPrimaryKey(Defectrecord record);

    List<String> selectTppe();
    List<String> selectdefectPart();
    List<String> selectdefectMode();
    List<String> selectspecificPart();
    List<String> selectremark();
}